# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DataBC
email: data@gov.bc.ca
description: > # this means to ignore newlines until "baseurl:"
  BC Government site to facilitate access and encourage the use of government data. Search the BC Data Catalogue and explore visualizations and links to featured datasets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://data.gov.bc.ca" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Exclude some directories from being included
# Excluding css/ & sass/ because we want control over it
#include: [".htaccess"]
exclude: ['css', '_sass', 'node_modules', 'Gruntfile.js', 'package.json', 'README.md', 'LICENSE', 'Dockerfile']

keep_files: ['_site/css', '_site/js', '_site/fonts']

collections:
  visualizations:
    output: false

# Serving
incremental: true
#detach: true
host: 0.0.0.0
